Develop
AKShipulya/Quadrangle pull request #1
Opened 2021-12-01 15:59 UTC by AKShipulya

2021-12-01 17:47 UTC, FilippStankevichTR requested changes

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/dao/DataReader.java
> +
finally { bufferedReader.close(); }

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/dao/DataValidator.java
> +public class DataValidator {
QuadrangleLineValidator

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/dao/DataValidator.java
> +    public static boolean isLinesValid(String line) {
isValid

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/entity/Quadrangle.java
> +        if (this == o) return true;
if (this == o)  {
return true;
}

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/entity/ShapePoint.java
> +public class ShapePoint {
Point

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/service/QuadrangleCreator.java
> +    private static final Logger LOGGER = LogManager.getLogger();
QuadrangleCreator.class

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/service/QuadrangleDirector.java
> +
Quadrangle quadrangle = creator.createQuadrangle(parsedLinesToDouble);

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/service/QuadrangleParametersValidator.java
> +    public static boolean areRectangleParametersValid(ShapePoint pointA, ShapePoint pointB,
isRectangleValid

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/service/QuadrangleService.java
> +            throw new QuadrangleException(ERROR_MESSAGE);
"Invalid Quadrangle!"

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/test/java/com/epam/quadrangle/service/QuadrangleCreatorTest.java
> +            coordinatesPoints.add(10.0);
Arrays.asList()

2021-12-01 17:47 UTC, FilippStankevichTR commented on src/test/java/com/epam/quadrangle/service/QuadrangleServiceTest.java
> +    private List<Double> coordinatesPoints;
private static final List<Double> COORDINATES = Array.asList<Double>(10.0, 10.0...

2021-12-03 07:10 UTC, AKShipulya commented on src/main/java/com/epam/quadrangle/service/QuadrangleCreator.java
> +    private static final Logger LOGGER = LogManager.getLogger();
I've tried to put the QuadrangleCreator.class in LogManager.getLogger() - nothing changed - the logger shows correct classes in their logs with and without this option

2021-12-25 13:31 UTC, ingenmech requested changes

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/QuadrangleDirector.java
> +    public List<QuadrangleObservable> read(String filePath) throws DataException, IOException, QuadrangleException {
you catch all of these exception in catch block, at this time you throw it in condition 
They should be logged, and you can return empty list if filePath.isEmpty()
if (filePath == null || filePath.isEmpty()) {
            throw new DataException("Invalid path to file with data");
        }
throws DataException, IOException, QuadrangleException

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/comparator/QuadrangleAreaComparator.java
> +            o1Area = calculator.calculateQuadrangleArea(o1);
dont throw exception from calculator, you have validator

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/comparator/QuadranglePerimeterComparator.java
> +            o1Area = calculator.calculateQuadranglePerimeter(o1);
naming o1 , firstObserver and etc

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/data/DataReader.java
> +            bufferedReader.close();
check when you close and use try catch

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/data/QuadrangleLineValidator.java
> +            throw new DataException("Invalid line of data!");
if line invalid dont throw exception return false

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/logic/QuadrangleCalculator.java
> +            throw new QuadrangleException("Invalid Quadrangle!");
if it invalid return false dont throw exception

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/logic/QuadrangleCalculator.java
> +            throw new QuadrangleException("Invalid Quadrangle!");
the same as previous

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/logic/QuadrangleCalculator.java
> +            throw new QuadrangleException("Invalid Quadrangle!");
the same

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/repository/specification/impl/AreaSpecification.java
> +    public AreaSpecification(double FROM_AREA, double TO_AREA) {
why do you use upper snake case, it is naming just for stack variable

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/repository/specification/impl/DistanceSpecification.java
> +        this.FROM_RANGE_X = FROM_RANGE_X;
why upper snake case?

2021-12-25 13:31 UTC, ingenmech commented on src/main/java/com/epam/quadrangle/repository/specification/impl/IdSpecification.java
> +        this.FROM_ID = FROM_ID;
?

2021-12-27 13:46 UTC, FilippStankevichTR approved these changes

2021-12-27 13:46 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/comparator/QuadranglePerimeterComparator.java
> +    public int compare(QuadrangleObservable o1, QuadrangleObservable o2) {
dont' use numbers in variable names

2021-12-27 13:46 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/comparator/QuadranglePerimeterComparator.java
> +            LOGGER.warn(e);
better to re-thow otherwise you will get a wrong result

2021-12-27 13:46 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/comparator/QuadranglePerimeterComparator.java
> +        double o1Area = 0.0;
no need in these definitions if you define variables inside catch, or probably you don't need this exception at all

2021-12-27 13:46 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/comparator/QuadranglePointACoordinateYComparator.java
> +        return Double.compare(o1.getPointA().getPointY(), o2.getPointA().getPointY());
create variabe for pointA

2021-12-27 13:46 UTC, FilippStankevichTR commented on src/main/java/com/epam/quadrangle/data/DataLinesParser.java
> +    private final QuadrangleLineValidator LINE_VALIDATOR;
should not be upper case

2021-12-27 14:09 UTC, AKShipulya commented on src/main/java/com/epam/quadrangle/repository/specification/impl/DistanceSpecification.java
> +        this.FROM_RANGE_X = FROM_RANGE_X;
this was caused by IDEA the wrong settings of constructor auto-creating, I didn't check it when created, unfortunately.

2021-12-27 14:10 UTC, AKShipulya commented on src/main/java/com/epam/quadrangle/repository/specification/impl/IdSpecification.java
> +        this.FROM_ID = FROM_ID;
this was caused by IDEA the wrong settings of constructor auto-creating, I didn't check it when created, unfortunately.

2021-12-27 14:14 UTC, AKShipulya commented on src/main/java/com/epam/quadrangle/comparator/QuadranglePerimeterComparator.java
> +    public int compare(QuadrangleObservable o1, QuadrangleObservable o2) {
it was noted by Maxim 2 days ago in this PR you can check it upper!
![изображение](https://user-images.githubusercontent.com/70636773/147479717-c81823cb-6642-4bc9-9a05-72a3c5310a58.png)

2022-05-13 13:22 UTC, merged